Logic added to the Calculator App
javierbotero/calculator pull request #4
Opened 2021-01-15 23:25 UTC by javierbotero

This pull request creates the logic of the calculator app implementing two JavaScript modules: calculate.js and operate.js which will be responsible for all calculations and those are included in the App component.

2021-01-16 11:38 UTC, sumancrest0001 commented
### Status: changes required :gear:

**Nice work @javierbotero :clap: ,**
We have to make a small change to get approved.
[Required] It seems that you forgot to import calculate.js in the App component. [Reference](https://microverse.pathwright.com/library/react-redux-v11/184438/path/step/106376018/)

2021-01-16 11:41 UTC, sumancrest0001 commented
[Optional] Please commit your code as frequently as possible which helps you to go back easily.

2021-01-16 11:44 UTC, sumancrest0001 requested changes
**Please make the necessary changes and submit the project for another review.
If you have any queries regarding the review, do message me on Slack.**

**Happy coding !!! :slightly_smiling_face:**

2021-01-16 11:47 UTC, sumancrest0001 commented on src/logic/calculate.js
> +export default function calculate(data, ButtonName) {
[Required] Please follow the JavaScript naming convention. **ButtonName** should be camelCase.

2021-01-17 07:55 UTC, Forison approved these changes
## Status::Approved✔️
#### Good job on addressing the issue raised in the previous review, calculator has been imported in App.jsx, kindly go ahead and , merge the branch and proceed to the next milestone👏👏👏.
#### Happy coding👨‍💻
Add Forison

2021-01-17 15:54 UTC, merged